version: "3"
services:
  web:
    hostname: web
    restart: always
    build: ./web
    networks: 
      - webnet
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
  result:
    hostname: result
    restart: always
    build: ./result
    networks:
      - webnet
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  worker:
    hostname: worker
    restart: always
    build: ./worker
    networks:
      - webnet
    depends_on:
      - postgres
      - rabbitmq
  postgres:
    hostname: postgres
    image: postgres
    restart: always
    networks:
      - webnet
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq
    privileged: true
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    restart: always
    networks:
      - webnet
    volumes:
      - /var/lib/rabbitmq:/var/lib/rabbitmq
networks:
  webnet:
    driver: bridge
